-- Simple tables

INSERT INTO ethnicity (id, name) VALUES
    (0, 'asian'),
    (1, 'black'),
    (2, 'hispanic'),
    (3, 'white');

INSERT INTO gender (id, name) VALUES
    (0, 'female'),
    (1, 'male');

INSERT INTO symptoms (family, fever, blue_whites, low_bp) VALUES
    (0, TRUE, TRUE, TRUE),
    (1, FALSE, TRUE, TRUE),
    (2, FALSE, FALSE, TRUE),
    (3, FALSE, FALSE, FALSE),
    (4, TRUE, FALSE, TRUE),
    (5, TRUE, FALSE, FALSE),
    (6, TRUE, TRUE, FALSE),
    (7, FALSE, TRUE, FALSE);

INSERT INTO disease (name, survival_rate) VALUES
    ('cabbage disease', 0.2),
    ('lettuce disease', 0.35);

-- Patient table

INSERT INTO patient (
    ethnicity,
    gender,
    symptoms_family,
    disease
)
VALUES
    (0, 1, 7, 'lettuce disease'),
    (1, 0, 3, NULL),
    (0, 0, 7, NULL),
    (2, 1, 0, NULL),
    (3, 1, 3, NULL),
    (0, 1, 7, 'lettuce disease'),
    (2, 0, 0, NULL),
    (1, 0, 4, 'cabbage disease'),
    (1, 1, 0, NULL),
    (1, 0, 3, NULL),
    (2, 0, 0, NULL),
    (0, 1, 7, 'lettuce disease'),
    (0, 1, 0, 'lettuce disease'),
    (0, 0, 7, NULL),
    (0, 1, 7, 'lettuce disease'),
    (3, 0, 0, NULL),
    (0, 0, 3, NULL),
    (1, 0, 7, NULL),
    (0, 0, 7, NULL),
    (3, 1, 0, NULL),
    (1, 1, 4, 'cabbage disease'),
    (3, 1, 2, NULL),
    (3, 1, 2, NULL),
    (0, 1, 3, 'cabbage disease'),
    (3, 0, 1, NULL),
    (2, 1, 1, NULL),
    (2, 1, 1, NULL),
    (3, 1, 0, 'lettuce disease'),
    (1, 0, 3, NULL),
    (3, 1, 0, 'cabbage disease'),
    (0, 1, 7, NULL),
    (3, 0, 5, NULL),
    (0, 0, 7, NULL),
    (3, 1, 4, 'cabbage disease'),
    (2, 1, 1, NULL),
    (3, 1, 2, NULL),
    (1, 0, 2, NULL),
    (0, 1, 1, NULL),
    (2, 0, 3, NULL),
    (1, 1, 4, NULL),
    (1, 0, 0, NULL),
    (1, 1, 0, NULL),
    (3, 1, 4, 'cabbage disease'),
    (2, 0, 2, NULL),
    (2, 1, 4, 'cabbage disease'),
    (2, 1, 6, NULL),
    (2, 1, 6, NULL),
    (2, 0, 7, NULL),
    (2, 0, 7, NULL),
    (0, 1, 0, NULL),
    (3, 0, 0, 'cabbage disease'),
    (1, 0, 2, NULL),
    (3, 1, 5, NULL),
    (2, 1, 4, NULL),
    (3, 1, 1, NULL),
    (2, 0, 4, NULL),
    (3, 1, 4, 'cabbage disease'),
    (0, 1, 4, 'lettuce disease'),
    (1, 1, 0, NULL),
    (1, 1, 7, 'lettuce disease'),
    (0, 0, 2, NULL),
    (3, 1, 3, NULL),
    (0, 0, 0, NULL),
    (1, 0, 2, NULL),
    (0, 1, 4, 'cabbage disease'),
    (3, 1, 2, 'cabbage disease'),
    (2, 0, 4, NULL),
    (2, 0, 1, NULL),
    (0, 1, 4, 'cabbage disease'),
    (0, 1, 3, NULL),
    (3, 1, 2, NULL),
    (1, 0, 4, 'cabbage disease'),
    (0, 1, 2, 'cabbage disease'),
    (1, 1, 4, 'cabbage disease'),
    (3, 1, 2, NULL),
    (2, 1, 4, 'cabbage disease'),
    (3, 1, 5, 'cabbage disease'),
    (3, 1, 4, 'cabbage disease'),
    (2, 0, 3, NULL),
    (3, 1, 4, 'cabbage disease'),
    (2, 1, 5, NULL),
    (3, 0, 7, NULL),
    (3, 1, 4, 'cabbage disease'),
    (1, 1, 3, NULL),
    (2, 1, 4, NULL),
    (0, 1, 7, 'lettuce disease'),
    (2, 0, 7, NULL),
    (3, 0, 5, NULL),
    (2, 1, 1, NULL),
    (2, 1, 3, NULL),
    (1, 0, 6, NULL),
    (2, 0, 5, NULL),
    (1, 0, 3, NULL),
    (2, 0, 7, NULL),
    (2, 1, 4, 'cabbage disease'),
    (2, 1, 4, NULL),
    (0, 0, 6, NULL),
    (0, 1, 3, NULL),
    (3, 1, 2, NULL),
    (2, 1, 5, NULL),
    (1, 1, 6, NULL);